### ISSUE TITLE
How to install it in Macbook pro

### ISSUE THREAD

**Issue by kpratik9** [cdominik/optool#1]

**Comment by cdominik** [comment]
Did you read the user guide?

**Comment by kpratik9** [comment]
Yes after reading user guide I have asked this question over here. Already installed it but getting an error: optool command not found.

Kindly post the proper steps in this thread to install it so that it can help other users as well.

**Comment by cdominik** [comment]
If you have compiled it successfully, you need to put the executable onto your binary execution path.
Or, if you are in the terminal in the same directory where the executable is located, you can also run it using

./optool .....

In general, if you are not putting it onto your execution path, you need to call it using the full path to the executable,
like

~/tmp/where/you/have/it/optool .....

**Comment by cdominik** [comment]
This means that optool is not in one of the directories that are on your
shell's search path for executable files.  If you are the the directory
where thecompiled executable is, you can run it like ./optool   . Otherwise
more it into something like ~/bin or /usr/local/bin and make sure that
these directories are on your binary path.  You can check this with

echo $PATH

But this is really basic unix/linux stuff and not an issue in the
installation instructions.

Regards

Carsten
